osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
    include:
        - os: osx
        - os: linux
          env: CC=clang CXX=clang++ npm_config_clang=1
        - os: win
        - arch: x86
        - arch: x64

cache:
    directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - ubuntu-wine
            - llvm-toolchain-precise-3.8
        packages:
            - wine1.8
            - icnsutils
            - graphicsmagick
            - xz-utils
            - rpm
            - mono-devel
            - ca-certificates-mono
            - gcc-multilib
            - g++-multilib
            - clang-3.8

install:
- nvm install 6
- npm install electron-builder
- npm install
- npm prune

script:
- npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
