osx_image: xcode7.3

sudo: required
dist: trusty

language: nodejs
nodejs:
    - "6"

matrix:
    - os: osx
    - os: linux

cache:
    directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-add-repository ppa:ubuntu-wine/ppa -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-add-repository ppa:likemartinma/osslsigncode -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install build-essential icnsutils graphicsmagick xz-utils rpm wine1.8 mono-devel ca-certificates-mono osslsigncode gcc-multilib g++-multilib -y --no-install-recommends; fi

install:
- npm install
- npm prune

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm run dist:win64; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm run dist:win32; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm run dist:linux64; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm run dist:linux32; fi
- if [[ "$TRAVIS_OS_NAME" == "osx"]; npm run dist:darwin; fi

branches:
  only:
      -travis
