sudo: required
dist: trusty

language: node_js
node_js:
    - "6"

os:
    - osx
    - linux

cache:
    directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron

before_install:
    - .travis/install-dependencies.sh

install:
- npm install
- npm prune

script:
    - .travis/build.sh

branches:
  only:
      - travis
